server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      # 静态路由配置
      routes:
        # 前端接口
        - id: http-service
          order: 1
          uri: http://localhost:8081
          predicates:
            - Path=/mall/**
          filters:
            - StripPrefix=1
