server:
  port: 8061

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: skywalking-demo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

feign:
  sentinel:
    enabled: true